# Generated by Django 4.2.3 on 2024-05-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64)),
                ("deal_amount", models.PositiveIntegerField(default=5)),
                ("duration", models.PositiveIntegerField(default=300)),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price of token when deal got created",
                        max_digits=20,
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price of token when deal got closed",
                        max_digits=20,
                    ),
                ),
                ("open_at", models.DateTimeField(auto_now_add=True)),
                ("close_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bear_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bear_deals",
                        to="users.profile",
                    ),
                ),
                (
                    "bull_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bull_deals",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "db_table": "deals",
            },
        ),
    ]
