# Generated by Django 4.2.3 on 2024-05-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matchmaking", "0002_deal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="close_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Price of token when deal got closed",
                max_digits=20,
                null=True,
            ),
        ),
    ]
