# Generated by Django 4.2.3 on 2024-05-18 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0001_initial"),
        ("matchmaking", "0003_alter_deal_close_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deals",
                to="tokens.token",
            ),
        ),
    ]
