# Generated by Django 4.2.3 on 2024-05-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_balance"),
        ("matchmaking", "0004_alter_deal_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="bear_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bear_deals",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="bull_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bull_deals",
                to="users.profile",
            ),
        ),
    ]
